# Generated by Django 3.0.1 on 2023-10-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllRecordsG18',
            fields=[
                ('file_name', models.CharField(blank=True, db_column='File_Name', max_length=30, null=True)),
                ('data_id', models.IntegerField(db_column='Data_Id', primary_key=True, serialize=False)),
                ('door_no', models.CharField(blank=True, db_column='Door_No', max_length=20, null=True)),
                ('device_sn', models.CharField(blank=True, db_column='Device_Sn', max_length=30, null=True)),
                ('get_time', models.DateTimeField(blank=True, db_column='Get_Time', null=True)),
                ('is_opendoor', models.IntegerField(blank=True, db_column='Is_OpenDoor', null=True)),
                ('is_fault', models.IntegerField(blank=True, db_column='Is_Fault', null=True)),
                ('is_normal', models.IntegerField(blank=True, db_column='Is_Normal', null=True)),
                ('stationid', models.IntegerField(blank=True, db_column='StationId', null=True)),
                ('updown', models.IntegerField(blank=True, db_column='UpDown', null=True)),
                ('original_speeddata', models.CharField(blank=True, db_column='Original_SpeedData', max_length=200, null=True)),
                ('original_torquedata', models.CharField(blank=True, db_column='Original_TorqueData', max_length=200, null=True)),
                ('original_angledata', models.CharField(blank=True, db_column='Original_AngleData', max_length=200, null=True)),
                ('original_temperaturedata', models.CharField(blank=True, db_column='Original_TemperatureData', max_length=200, null=True)),
                ('change_speeddata', models.CharField(blank=True, db_column='Change_SpeedData', max_length=200, null=True)),
                ('change_torquedata', models.CharField(blank=True, db_column='Change_TorqueData', max_length=200, null=True)),
                ('change_angledata', models.CharField(blank=True, db_column='Change_AngleData', max_length=200, null=True)),
                ('change_temperaturedata', models.CharField(blank=True, db_column='Change_TemperatureData', max_length=200, null=True)),
                ('dcu_data', models.CharField(blank=True, db_column='DCU_Data', max_length=10, null=True)),
                ('datacreated', models.DateTimeField(blank=True, db_column='DataCreated', null=True)),
            ],
            options={
                'db_table': 'all_records_g18',
                'managed': False,
            },
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(default=20, max_length=10),
        ),
    ]
